ALEC-94: Update health check command
OpenNMS/alec pull request #130
Opened 2023-03-30 19:19 UTC by emarsh1995

- Update `admin/distributed_install.adoc`
- Update `install/basic_install.adoc`, `/pre_install.adoc`
- Update `reference/datasources/kafka.adoc`

## External References

- Jira (Issue Tracker): https://opennms.atlassian.net/browse/ALEC-94

2023-03-30 20:06 UTC, agalue submitted a review, later dismissed
It's been years since I last used ALEC, but the changes look good to me from what I remember.

2023-03-30 22:22 UTC, Bonrob2 requested changes
minor changes, thank you!

2023-03-30 22:22 UTC, Bonrob2 commented on docs/modules/admin/pages/distributed_install.adoc
> +The steps should be completed using the OpenNMS Karaf shell.
```suggestion
You should use the OpenNMS Karaf shell to complete these steps. 
```

2023-03-30 22:22 UTC, Bonrob2 commented on docs/modules/admin/pages/distributed_install.adoc
> +. Configure the feature set to be installed when OpenNMS starts:
```suggestion
. Configure the feature set to install when OpenNMS starts:
```

2023-03-30 22:22 UTC, Bonrob2 commented on docs/modules/admin/pages/distributed_install.adoc
> +. Configure the feature set to be installed when Sentinel starts:
```suggestion
. Configure the feature set to install when Sentinel starts:
```

2023-03-30 22:22 UTC, Bonrob2 commented on docs/modules/install/pages/pre_install.adoc
> +If it returns `Oh no, something is wrong`, you must address the underlying problem before moving forward.
```suggestion
If it returns `Oh no, something is wrong`, you must address the underlying problem before continuing.
```

2023-03-30 22:22 UTC, Bonrob2 commented on docs/modules/install/pages/pre_install.adoc
> +This change is effected the next time OpenNMS restarts.
```suggestion
This change occurs the next time OpenNMS restarts.
```

2023-03-31 15:38 UTC, Bonrob2 approved these changes
LGTM!

2023-04-03 18:29 UTC, merged